// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChZEqV7CglNoEGQbJIxuGmwZRhaqbaK2o',
    appId: '1:782189465310:web:298fce78f735102d7fbc4f',
    messagingSenderId: '782189465310',
    projectId: 'steadysteps-7c44f',
    authDomain: 'steadysteps-7c44f.firebaseapp.com',
    storageBucket: 'steadysteps-7c44f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0yYVqbZfgobUEkqOgBZ9IENRDNkgcguk',
    appId: '1:782189465310:android:436a36564faaf6137fbc4f',
    messagingSenderId: '782189465310',
    projectId: 'steadysteps-7c44f',
    storageBucket: 'steadysteps-7c44f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPrJDfdSD3WwY2eGNTJ3aav-mcPv3qdvM',
    appId: '1:782189465310:ios:6b82eb8e876663457fbc4f',
    messagingSenderId: '782189465310',
    projectId: 'steadysteps-7c44f',
    storageBucket: 'steadysteps-7c44f.appspot.com',
    androidClientId: '782189465310-0m9et84ctom5g8agqm4q8tijsi92asfm.apps.googleusercontent.com',
    iosClientId: '782189465310-u8q1odgblj7laro84via4q38o6btp9m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.steadysteps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPrJDfdSD3WwY2eGNTJ3aav-mcPv3qdvM',
    appId: '1:782189465310:ios:6b82eb8e876663457fbc4f',
    messagingSenderId: '782189465310',
    projectId: 'steadysteps-7c44f',
    storageBucket: 'steadysteps-7c44f.appspot.com',
    androidClientId: '782189465310-0m9et84ctom5g8agqm4q8tijsi92asfm.apps.googleusercontent.com',
    iosClientId: '782189465310-u8q1odgblj7laro84via4q38o6btp9m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.steadysteps',
  );
}
